---
name: carvel-on-bosh-demo

instance_groups:
- name: server
  azs: ((azs))
  instances: 1
  vm_type: ((vm_type))
  persistent_disk_type: 102400
  stemcell: default
  networks: [{name: ((network))}]
  jobs:
  - { name: k3s-server,       release: k3s-wrapper }
  - { name: k3s-packages,     release: k3s-packages }
  properties:
    k3s:
      token: ((k3s-token))

- name: worker
  azs: ((azs))
  instances: 1
  vm_type: ((vm_type))
  stemcell: default
  networks: [{name: ((network))}]
  jobs:
  - { name: k3s-agent,        release: k3s-wrapper }
  - { name: k3s-packages,     release: k3s-packages }
  properties:
    k3s:
      token: ((k3s-token))

variables:
- name: k3s-token
  type: password

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: k3s-wrapper
  version: 0.8.5
  url: https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease/releases/download/v0.8.5/k3s-wrapper-0.8.5.tgz
- name: k3s-packages
  version: 1.31.1+k3s1
  url: https://github.com/orange-cloudfoundry/k3s-packages-boshrelease/releases/download/1.31.1%2Bk3s1/k3s-packages-1.31.1+k3s1.tgz
