---
name: carvel-on-bosh-demo

instance_groups:
- name: server
  azs: ((azs))
  instances: 1
  vm_type: ((vm_type))
  persistent_disk_type: 102400
  stemcell: default
  networks: [{name: ((network))}]
  jobs:
  - { name: k3s-server,       release: k3s-wrapper }
  - { name: k3s-packages,     release: k3s-packages }
  - { name: registry-data,    release: registry-data }
  - name: registry
    release: docker-registry
    custom_provider_definitions:
    - name: registry
      type: address
      shared: true
    provides:
      registry:
        aliases:
        - domain: registry.bosh
          health_filter: "healthy"
        as: registry-address
  properties:
    docker:
      registry:
        bind: 0.0.0.0
        port: 5000
        ssl:
          cert: ((registry_tls.certificate))
          key: ((registry_tls.private_key))
        root: /var/vcap/packages/registry-data
    k3s:
      token: ((k3s-token))
      additional-manifests:
      - |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: kapp-controller
      # - |
      #     apiVersion: v1
      #     kind: Secret
      #       metadata:
      #       name: kapp-controller-config
      #       namespace: kapp-controller
      #     stringData:
      #       caCerts: |
      #         ((registry_tls.ca))
- name: worker
  azs: ((azs))
  instances: 1
  vm_type: ((vm_type))
  stemcell: default
  networks: [{name: ((network))}]
  jobs:
  - { name: k3s-agent,        release: k3s-wrapper }
  - { name: k3s-packages,     release: k3s-packages }
  properties:
    k3s:
      token: ((k3s-token))

variables:
- name: k3s-token
  type: password
- name: registry_ca
  type: certificate
  update_mode: converge
  options:
    common_name: ca
    is_ca: true
- name: registry_tls
  type: certificate
  update_mode: converge
  options:
    ca: registry_ca
    alternative_names:
    - "localhost"
    common_name: registry.bosh
  consumes:
    alternative_name:
      from: registry-address

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: k3s-wrapper
  version: 0.8.5
  url: https://github.com/orange-cloudfoundry/k3s-wrapper-boshrelease/releases/download/v0.8.5/k3s-wrapper-0.8.5.tgz
- name: k3s-packages
  version: 1.31.1+k3s1
  url: https://github.com/orange-cloudfoundry/k3s-packages-boshrelease/releases/download/1.31.1%2Bk3s1/k3s-packages-1.31.1+k3s1.tgz
- name:    docker-registry
  version: 3.6.0
  url:     https://github.com/cloudfoundry-community/docker-registry-boshrelease/releases/download/v3.6.0/docker-registry-3.6.0.tgz
  sha1:    2f09ca4f50c0129fdb8a7b84fe6d74b085c109c4
- name: registry-data
  version: latest
